let mock = [{
        id: 0,
        timesVisited: 0,
        name_1: 'Talbot',
        name_2: 'Crimson',
        mayor: 'Goudard',
        lat: 5.4252,
        'long': 89.3040,
        population: 752,
        population_mult: 21,
        food: 8,
        lumber: 27,
        ore: 91,
        aether: 716,
        luxury: 1731,
        text: 'Ah, the town looks just like it used to.',
    },
    {
        id: 1,
        timesVisited: 0,
        name_1: 'Clemmie',
        name_2: 'Goldenrod',
        mayor: 'Simo',
        lat: 69.6473,
        'long': 39.1423,
        population: 769,
        population_mult: 14,
        food: 3,
        lumber: 20,
        ore: 81,
        aether: 739,
        luxury: 1727,
        text: 'Some youths in the road were gossiping about Dread Pirate Ralph as I walked by. One said, "They are the fiercest pirate around, and anyone who picks a fight with them is plain stupid!" another said, "Why would someone want to pick fights anyways? What a jerk." The first replied, "Ah, but even though they try to live a peaceful life, other people keep messing with them. Thats why they always fly the emerald skull flag- so that anyone who wants peace can stay away."',
    },
    {
        id: 2,
        timesVisited: 0,
        name_1: 'Matilda',
        name_2: 'Crimson',
        mayor: 'Fossey',
        lat: 62.4448,
        'long': 19.9096,
        population: 785,
        population_mult: 13,
        food: 1,
        lumber: 16,
        ore: 72,
        aether: 743,
        luxury: 1752,
        text: 'A begger stopped me on my way to the market. They asked, "Whats is it that humans find most valuable?" I was at a loss for words, so they answered their own question and said, "That which they can see, but cannot touch. That is why art is prettier the farther you are from it." I kept thinking about that philosophy throughout the day.',
    },
    {
        id: 3,
        timesVisited: 0,
        name_1: 'Locke',
        name_2: 'Red',
        mayor: 'Barca',
        lat: 82.5637,
        'long': 18.4458,
        population: 706,
        population_mult: 18,
        food: 2,
        lumber: 24,
        ore: 81,
        aether: 793,
        luxury: 1743,
        text: 'Today I saw a shark in the ocean.',
    },
    {
        id: 4,
        timesVisited: 0,
        name_1: 'Faunie',
        name_2: 'Indigo',
        mayor: 'Barwack',
        lat: 25.5723,
        'long': 43.2868,
        population: 697,
        population_mult: 16,
        food: 7,
        lumber: 18,
        ore: 84,
        aether: 751,
        luxury: 1686,
        text: 'A pidgeon pooped above me today, but it fell just in front of me. If it had been another few centimeters...',
    },
    {
        id: 5,
        timesVisited: 0,
        name_1: 'Tamara',
        name_2: 'Crimson',
        mayor: 'Rault',
        lat: 45.8026,
        'long': 95.4134,
        population: 771,
        population_mult: 22,
        food: 6,
        lumber: 19,
        ore: 85,
        aether: 689,
        luxury: 717,
        text: 'Today a shark in the ocean saw me.',
    },
    {
        id: 6,
        timesVisited: 0,
        name_1: 'Cletis',
        name_2: 'Violet',
        mayor: 'Ambrosini',
        lat: 45.8590,
        'long': 37.8349,
        population: 785,
        population_mult: 26,
        food: 4,
        lumber: 13,
        ore: 81,
        aether: 683,
        luxury: 1779,
        text: 'Haha, I feel on top of the world! Well, at least on top of the ocean.',
    },
    {
        id: 7,
        timesVisited: 0,
        name_1: 'Rosabel',
        name_2: 'Turquoise',
        mayor: 'Fishpond',
        lat: 40.6141,
        'long': 21.1100,
        population: 729,
        population_mult: 11,
        food: 4,
        lumber: 20,
        ore: 70,
        aether: 748,
        luxury: 1751,
        text: 'In the distance, I saw a ship whose flag pictured a skull with an emerald in its eye. Could it be...?',
    },
    {
        id: 8,
        timesVisited: 0,
        name_1: 'Jewell',
        name_2: 'Violet',
        mayor: 'Jeavons',
        lat: 22.5768,
        'long': 59.7341,
        population: 725,
        population_mult: 13,
        food: 3,
        lumber: 16,
        ore: 82,
        aether: 742,
        luxury: 1747,
        text: 'I saw the most amazing shooting star the other night!',
    },
    {
        id: 9,
        timesVisited: 0,
        name_1: 'Mollee',
        name_2: 'Maroon',
        mayor: 'Tingcomb',
        lat: 82.6691,
        'long': 39.5147,
        population: 776,
        population_mult: 15,
        food: 4,
        lumber: 19,
        ore: 95,
        aether: 738,
        luxury: 1720,
        text: 'I saw someone very pretty on the docks today! They were looking away though, and did not see me.',
    },
    {
        id: 10,
        timesVisited: 0,
        name_1: 'Auberta',
        name_2: 'Maroon',
        mayor: 'Mawd',
        lat: 39.4158,
        'long': 79.9404,
        population: 731,
        population_mult: 13,
        food: 5,
        lumber: 22,
        ore: 90,
        aether: 749,
        luxury: 1715,
        text: 'Brrr, the seas sure were cold pulling into port.',
    },
    {
        id: 11,
        timesVisited: 0,
        name_1: 'Maryann',
        name_2: 'Teal',
        mayor: 'Lockhart',
        lat: 10.7441,
        'long': 9.4954,
        population: 764,
        population_mult: 19,
        food: 6,
        lumber: 15,
        ore: 71,
        aether: 751,
        luxury: 1769,
        text: 'Someone on this island cussed me out What a jerk.',
    },
    {
        id: 12,
        timesVisited: 0,
        name_1: 'Moises',
        name_2: 'Turquoise',
        mayor: 'Beeson',
        lat: 71.8720,
        'long': 47.0600,
        population: 747,
        population_mult: 14,
        food: 9,
        lumber: 28,
        ore: 75,
        aether: 725,
        luxury: 1783,
        text: 'Today I saw a shark in the ocean.',
    },
    {
        id: 13,
        timesVisited: 0,
        name_1: 'Townie',
        name_2: 'Green',
        mayor: 'Pollastrino',
        lat: 93.0228,
        'long': 54.4098,
        population: 741,
        population_mult: 19,
        food: 4,
        lumber: 13,
        ore: 62,
        aether: 735,
        luxury: 1750,
        text: 'I thought, "Hey, I have a boat. Why not leave?"',
    },
    {
        id: 14,
        timesVisited: 0,
        name_1: 'Murdoch',
        name_2: 'Khaki',
        mayor: 'Coulthart',
        lat: 36.4908,
        'long': 76.2989,
        population: 744,
        population_mult: 9,
        food: 7,
        lumber: 14,
        ore: 81,
        aether: 782,
        luxury: 1708,
        text: 'Today I was very misty, and I almost crashed the ship pulling into port. That would have been a real mess.',
    },
    {
        id: 15,
        timesVisited: 0,
        name_1: 'Merrill',
        name_2: 'Indigo',
        mayor: 'Ciobutaro',
        lat: 36.6449,
        'long': 90.2278,
        population: 702,
        population_mult: 11,
        food: 7,
        lumber: 20,
        ore: 94,
        aether: 766,
        luxury: 1758,
        text: 'We crossed paths with some friendly merchants out at sea this morning. They offered us some food, but the price was a little high, so I declined.',
    },
    {
        id: 16,
        timesVisited: 0,
        name_1: 'Benoite',
        name_2: 'Purple',
        mayor: 'Bonwick',
        lat: 74.7175,
        'long': 68.3393,
        population: 798,
        population_mult: 18,
        food: 2,
        lumber: 23,
        ore: 89,
        aether: 762,
        luxury: 1727,
        text: 'That merchant smirked as I left. I think I should have haggled the price down further...',
    },
    {
        id: 17,
        timesVisited: 0,
        name_1: 'Ronnica',
        name_2: 'Yellow',
        mayor: 'Tinwell',
        lat: 32.3976,
        'long': 46.2765,
        population: 754,
        population_mult: 13,
        food: 7,
        lumber: 27,
        ore: 66,
        aether: 739,
        luxury: 1722,
        text: 'Today was uneventful.',
    },
    {
        id: 18,
        timesVisited: 0,
        name_1: 'Breena',
        name_2: 'Goldenrod',
        mayor: 'Cossell',
        lat: 18.5800,
        'long': 54.4193,
        population: 707,
        population_mult: 13,
        food: 7,
        lumber: 15,
        ore: 87,
        aether: 766,
        luxury: 1710,
        text: 'I lost my favorite pen. Hopefully I will find it on my ship later...',
    },
    {
        id: 19,
        timesVisited: 0,
        name_1: 'Odette',
        name_2: 'Puce',
        mayor: 'Chuck',
        lat: 7.7164,
        'long': 20.4496,
        population: 710,
        population_mult: 11,
        food: 3,
        lumber: 22,
        ore: 92,
        aether: 719,
        luxury: 1752,
        text: '20',
    },
    {
        id: 20,
        timesVisited: 0,
        name_1: 'Evelyn',
        name_2: 'Purple',
        mayor: 'Kemshell',
        lat: 75.2082,
        'long': 39.7556,
        population: 755,
        population_mult: 14,
        food: 3,
        lumber: 23,
        ore: 63,
        aether: 792,
        luxury: 1738,
        text: '21.',
    },
    {
        id: 21,
        timesVisited: 0,
        name_1: 'Aleta',
        name_2: 'Red',
        mayor: 'Kerslake',
        lat: 94.6105,
        'long': 55.9228,
        population: 692,
        population_mult: 12,
        food: 1,
        lumber: 20,
        ore: 97,
        aether: 721,
        luxury: 1781,
        text: '22.',
    },
    {
        id: 22,
        timesVisited: 0,
        name_1: 'Leonore',
        name_2: 'Violet',
        mayor: 'Kingwell',
        lat: 39.6727,
        'long': 95.3921,
        population: 766,
        population_mult: 17,
        food: 7,
        lumber: 18,
        ore: 71,
        aether: 731,
        luxury: 1746,
        text: '23.',
    },
    {
        id: 23,
        timesVisited: 0,
        name_1: 'Anallese',
        name_2: 'Maroon',
        mayor: 'Crowcombe',
        lat: 81.0401,
        'long': 54.6030,
        population: 763,
        population_mult: 19,
        food: 3,
        lumber: 21,
        ore: 76,
        aether: 762,
        luxury: 1796,
        text: '24.',
    },
    {
        id: 24,
        timesVisited: 0,
        name_1: 'Della',
        name_2: 'Blue',
        mayor: 'Elesander',
        lat: 10.5967,
        'long': 28.5271,
        population: 778,
        population_mult: 13,
        food: 5,
        lumber: 21,
        ore: 72,
        aether: 790,
        luxury: 1753,
        text: '25.',
    },
    {
        id: 25,
        timesVisited: 0,
        name_1: 'Juieta',
        name_2: 'Pink',
        mayor: 'Tessington',
        lat: 88.4178,
        'long': 45.3625,
        population: 763,
        population_mult: 13,
        food: 4,
        lumber: 14,
        ore: 83,
        aether: 724,
        luxury: 1746,
        text: '26.',
    },
    {
        id: 26,
        timesVisited: 0,
        name_1: 'Jenni',
        name_2: 'Mauv',
        mayor: 'Pedder',
        lat: 10.0599,
        'long': 54.5096,
        population: 721,
        population_mult: 14,
        food: 3,
        lumber: 16,
        ore: 75,
        aether: 741,
        luxury: 1767,
        text: '27.',
    },
    {
        id: 27,
        timesVisited: 0,
        name_1: 'Bartie',
        name_2: 'Green',
        mayor: 'Ollander',
        lat: 37.9001,
        'long': 84.7585,
        population: 679,
        population_mult: 23,
        food: 2,
        lumber: 15,
        ore: 78,
        aether: 730,
        luxury: 1698,
        text: '28.',
    },
    {
        id: 28,
        timesVisited: 0,
        name_1: 'Keelby',
        name_2: 'Yellow',
        mayor: 'Solano',
        lat: 56.6022,
        'long': 86.6878,
        population: 757,
        population_mult: 9,
        food: 7,
        lumber: 20,
        ore: 75,
        aether: 758,
        luxury: 1743,
        text: '29.',
    },
    {
        id: 29,
        timesVisited: 0,
        name_1: 'Morlee',
        name_2: 'Teal',
        mayor: 'Labet',
        lat: 92.6000,
        'long': 40.0742,
        population: 732,
        population_mult: 19,
        food: 1,
        lumber: 11,
        ore: 89,
        aether: 767,
        luxury: 1793,
        text: '30.',
    }
]

export default mock;